// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RosaryForToday.Infrastructure.Data;

#nullable disable

namespace RosaryForToday.Infrastructure.Migrations
{
    [DbContext(typeof(RosaryDbContext))]
    [Migration("20251110155701_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("RosaryForToday.Domain.Entities.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Languages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "en",
                            Name = "English"
                        },
                        new
                        {
                            Id = 2,
                            Code = "pl",
                            Name = "Polish"
                        });
                });

            modelBuilder.Entity("RosaryForToday.Domain.Entities.RosaryDaySchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RosaryTypeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RosaryTypeId", "DayOfWeek")
                        .IsUnique();

                    b.ToTable("RosaryDaySchedules");
                });

            modelBuilder.Entity("RosaryForToday.Domain.Entities.RosaryReflection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("LanguageId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RosaryTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("RosaryTypeId");

                    b.ToTable("RosaryReflections");
                });

            modelBuilder.Entity("RosaryForToday.Domain.Entities.RosaryType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("LanguageId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.ToTable("RosaryTypes");
                });

            modelBuilder.Entity("RosaryForToday.Domain.Entities.RosaryDaySchedule", b =>
                {
                    b.HasOne("RosaryForToday.Domain.Entities.RosaryType", "RosaryType")
                        .WithMany("RosaryDaySchedules")
                        .HasForeignKey("RosaryTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RosaryType");
                });

            modelBuilder.Entity("RosaryForToday.Domain.Entities.RosaryReflection", b =>
                {
                    b.HasOne("RosaryForToday.Domain.Entities.Language", "Language")
                        .WithMany("RosaryReflections")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RosaryForToday.Domain.Entities.RosaryType", "RosaryType")
                        .WithMany("RosaryReflections")
                        .HasForeignKey("RosaryTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("RosaryType");
                });

            modelBuilder.Entity("RosaryForToday.Domain.Entities.RosaryType", b =>
                {
                    b.HasOne("RosaryForToday.Domain.Entities.Language", "Language")
                        .WithMany("RosaryTypes")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Language");
                });

            modelBuilder.Entity("RosaryForToday.Domain.Entities.Language", b =>
                {
                    b.Navigation("RosaryReflections");

                    b.Navigation("RosaryTypes");
                });

            modelBuilder.Entity("RosaryForToday.Domain.Entities.RosaryType", b =>
                {
                    b.Navigation("RosaryDaySchedules");

                    b.Navigation("RosaryReflections");
                });
#pragma warning restore 612, 618
        }
    }
}
