// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RosaryForToday.Infrastructure.Data;

#nullable disable

namespace RosaryForToday.Infrastructure.Migrations
{
    [DbContext(typeof(RosaryDbContext))]
    [Migration("20251120185437_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("RosaryForToday.Domain.Entities.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Languages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "EN",
                            Name = "English"
                        },
                        new
                        {
                            Id = 2,
                            Code = "PL",
                            Name = "Polski"
                        });
                });

            modelBuilder.Entity("RosaryForToday.Domain.Entities.RosaryDaySchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LanguageId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RosaryTypeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("RosaryTypeId", "DayOfWeek")
                        .IsUnique();

                    b.ToTable("RosaryDaySchedules");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DayOfWeek = 1,
                            LanguageId = 2,
                            RosaryTypeId = 1
                        },
                        new
                        {
                            Id = 2,
                            DayOfWeek = 1,
                            LanguageId = 1,
                            RosaryTypeId = 5
                        },
                        new
                        {
                            Id = 3,
                            DayOfWeek = 2,
                            LanguageId = 2,
                            RosaryTypeId = 2
                        },
                        new
                        {
                            Id = 4,
                            DayOfWeek = 2,
                            LanguageId = 1,
                            RosaryTypeId = 6
                        },
                        new
                        {
                            Id = 5,
                            DayOfWeek = 3,
                            LanguageId = 2,
                            RosaryTypeId = 4
                        },
                        new
                        {
                            Id = 6,
                            DayOfWeek = 3,
                            LanguageId = 1,
                            RosaryTypeId = 8
                        },
                        new
                        {
                            Id = 7,
                            DayOfWeek = 4,
                            LanguageId = 2,
                            RosaryTypeId = 3
                        },
                        new
                        {
                            Id = 8,
                            DayOfWeek = 4,
                            LanguageId = 1,
                            RosaryTypeId = 7
                        },
                        new
                        {
                            Id = 9,
                            DayOfWeek = 5,
                            LanguageId = 2,
                            RosaryTypeId = 2
                        },
                        new
                        {
                            Id = 10,
                            DayOfWeek = 5,
                            LanguageId = 1,
                            RosaryTypeId = 6
                        },
                        new
                        {
                            Id = 11,
                            DayOfWeek = 6,
                            LanguageId = 2,
                            RosaryTypeId = 1
                        },
                        new
                        {
                            Id = 12,
                            DayOfWeek = 6,
                            LanguageId = 1,
                            RosaryTypeId = 5
                        },
                        new
                        {
                            Id = 13,
                            DayOfWeek = 0,
                            LanguageId = 2,
                            RosaryTypeId = 4
                        },
                        new
                        {
                            Id = 14,
                            DayOfWeek = 0,
                            LanguageId = 1,
                            RosaryTypeId = 8
                        });
                });

            modelBuilder.Entity("RosaryForToday.Domain.Entities.RosaryReflection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("LanguageId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RosaryTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("RosaryTypeId");

                    b.ToTable("RosaryReflections");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "n/a",
                            LanguageId = 2,
                            RosaryTypeId = 1,
                            Title = "Zwiastowanie Pańskie"
                        },
                        new
                        {
                            Id = 2,
                            Content = "n/a",
                            LanguageId = 2,
                            RosaryTypeId = 1,
                            Title = "Nawiedzenie św. Elżbiety"
                        },
                        new
                        {
                            Id = 3,
                            Content = "n/a",
                            LanguageId = 2,
                            RosaryTypeId = 1,
                            Title = "Narodzenie Pana Jezusa"
                        },
                        new
                        {
                            Id = 4,
                            Content = "n/a",
                            LanguageId = 2,
                            RosaryTypeId = 1,
                            Title = "Ofiarowanie w świątyni"
                        },
                        new
                        {
                            Id = 5,
                            Content = "n/a",
                            LanguageId = 2,
                            RosaryTypeId = 1,
                            Title = "Odnalezienie Jezusa w świątyni"
                        },
                        new
                        {
                            Id = 6,
                            Content = "n/a",
                            LanguageId = 2,
                            RosaryTypeId = 2,
                            Title = "Modlitwa w Ogrójcu"
                        },
                        new
                        {
                            Id = 7,
                            Content = "n/a",
                            LanguageId = 2,
                            RosaryTypeId = 2,
                            Title = "Biczowanie Pana Jezusa"
                        },
                        new
                        {
                            Id = 8,
                            Content = "n/a",
                            LanguageId = 2,
                            RosaryTypeId = 2,
                            Title = "Cierniem Ukoronowanie"
                        },
                        new
                        {
                            Id = 9,
                            Content = "n/a",
                            LanguageId = 2,
                            RosaryTypeId = 2,
                            Title = "Droga Krzyżowa"
                        },
                        new
                        {
                            Id = 10,
                            Content = "n/a",
                            LanguageId = 2,
                            RosaryTypeId = 2,
                            Title = "Ukrzyżowanie i śmierć Pana Jezusa"
                        },
                        new
                        {
                            Id = 11,
                            Content = "n/a",
                            LanguageId = 2,
                            RosaryTypeId = 3,
                            Title = "Chrzest Jezusa w Jordanie"
                        },
                        new
                        {
                            Id = 12,
                            Content = "n/a",
                            LanguageId = 2,
                            RosaryTypeId = 3,
                            Title = "Objawienie się Jezusa w Kanie Galilejskiej"
                        },
                        new
                        {
                            Id = 13,
                            Content = "n/a",
                            LanguageId = 2,
                            RosaryTypeId = 3,
                            Title = "Głoszenie Królestwa Bożego"
                        },
                        new
                        {
                            Id = 14,
                            Content = "n/a",
                            LanguageId = 2,
                            RosaryTypeId = 3,
                            Title = "Przemienienie Pańskie"
                        },
                        new
                        {
                            Id = 15,
                            Content = "n/a",
                            LanguageId = 2,
                            RosaryTypeId = 3,
                            Title = "Ustanowienie Eucharystii"
                        },
                        new
                        {
                            Id = 16,
                            Content = "n/a",
                            LanguageId = 2,
                            RosaryTypeId = 4,
                            Title = "Zmartwychwstanie Jezusa"
                        },
                        new
                        {
                            Id = 17,
                            Content = "n/a",
                            LanguageId = 2,
                            RosaryTypeId = 4,
                            Title = "Wniebowstąpienie Pana"
                        },
                        new
                        {
                            Id = 18,
                            Content = "n/a",
                            LanguageId = 2,
                            RosaryTypeId = 4,
                            Title = "Zesłanie Ducha Świętego"
                        },
                        new
                        {
                            Id = 19,
                            Content = "n/a",
                            LanguageId = 2,
                            RosaryTypeId = 4,
                            Title = "Wniebowzięcie Najświętszej Maryi Panny"
                        },
                        new
                        {
                            Id = 20,
                            Content = "n/a",
                            LanguageId = 2,
                            RosaryTypeId = 4,
                            Title = "Ukoronowanie Maryi na Królową Nieba i Ziemi"
                        },
                        new
                        {
                            Id = 21,
                            Content = "n/a",
                            LanguageId = 1,
                            RosaryTypeId = 5,
                            Title = "The Annunciation"
                        },
                        new
                        {
                            Id = 22,
                            Content = "n/a",
                            LanguageId = 1,
                            RosaryTypeId = 5,
                            Title = "The Visitation"
                        },
                        new
                        {
                            Id = 23,
                            Content = "n/a",
                            LanguageId = 1,
                            RosaryTypeId = 5,
                            Title = "The Nativity (Birth of Our Lord)"
                        },
                        new
                        {
                            Id = 24,
                            Content = "n/a",
                            LanguageId = 1,
                            RosaryTypeId = 5,
                            Title = "The Presentation"
                        },
                        new
                        {
                            Id = 25,
                            Content = "n/a",
                            LanguageId = 1,
                            RosaryTypeId = 5,
                            Title = "The Finding in the Temple"
                        },
                        new
                        {
                            Id = 26,
                            Content = "n/a",
                            LanguageId = 1,
                            RosaryTypeId = 6,
                            Title = "The Agony in the Garden"
                        },
                        new
                        {
                            Id = 27,
                            Content = "n/a",
                            LanguageId = 1,
                            RosaryTypeId = 6,
                            Title = "The Scourging at the Pillar"
                        },
                        new
                        {
                            Id = 28,
                            Content = "n/a",
                            LanguageId = 1,
                            RosaryTypeId = 6,
                            Title = "The Crowning with Thorns"
                        },
                        new
                        {
                            Id = 29,
                            Content = "n/a",
                            LanguageId = 1,
                            RosaryTypeId = 6,
                            Title = "The Carrying of the Cross"
                        },
                        new
                        {
                            Id = 30,
                            Content = "n/a",
                            LanguageId = 1,
                            RosaryTypeId = 6,
                            Title = "The Crucifixion and Death of Our Lord"
                        },
                        new
                        {
                            Id = 31,
                            Content = "n/a",
                            LanguageId = 1,
                            RosaryTypeId = 7,
                            Title = "The Baptism of Jesus in the Jordan"
                        },
                        new
                        {
                            Id = 32,
                            Content = "n/a",
                            LanguageId = 1,
                            RosaryTypeId = 7,
                            Title = "The Wedding at Cana"
                        },
                        new
                        {
                            Id = 33,
                            Content = "n/a",
                            LanguageId = 1,
                            RosaryTypeId = 7,
                            Title = "The Proclamation of the Kingdom of God"
                        },
                        new
                        {
                            Id = 34,
                            Content = "n/a",
                            LanguageId = 1,
                            RosaryTypeId = 7,
                            Title = "The Transfiguration"
                        },
                        new
                        {
                            Id = 35,
                            Content = "n/a",
                            LanguageId = 1,
                            RosaryTypeId = 7,
                            Title = "The Institution of the Eucharist"
                        },
                        new
                        {
                            Id = 36,
                            Content = "n/a",
                            LanguageId = 1,
                            RosaryTypeId = 8,
                            Title = "The Resurrection"
                        },
                        new
                        {
                            Id = 37,
                            Content = "n/a",
                            LanguageId = 1,
                            RosaryTypeId = 8,
                            Title = "The Ascension"
                        },
                        new
                        {
                            Id = 38,
                            Content = "n/a",
                            LanguageId = 1,
                            RosaryTypeId = 8,
                            Title = "The Descent of the Holy Spirit (Pentecost)"
                        },
                        new
                        {
                            Id = 39,
                            Content = "n/a",
                            LanguageId = 1,
                            RosaryTypeId = 8,
                            Title = "The Assumption of the Blessed Virgin Mary"
                        },
                        new
                        {
                            Id = 40,
                            Content = "n/a",
                            LanguageId = 1,
                            RosaryTypeId = 8,
                            Title = "The Coronation of the Blessed Virgin Mary as Queen of Heaven and Earth"
                        });
                });

            modelBuilder.Entity("RosaryForToday.Domain.Entities.RosaryType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("LanguageId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.ToTable("RosaryTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LanguageId = 2,
                            Name = "Tajemnice Radosne"
                        },
                        new
                        {
                            Id = 2,
                            LanguageId = 2,
                            Name = "Tajemnice Bolesne"
                        },
                        new
                        {
                            Id = 3,
                            LanguageId = 2,
                            Name = "Tajemnice Światła"
                        },
                        new
                        {
                            Id = 4,
                            LanguageId = 2,
                            Name = "Tajemnice Chwalebne"
                        });
                });

            modelBuilder.Entity("RosaryForToday.Domain.Entities.RosaryDaySchedule", b =>
                {
                    b.HasOne("RosaryForToday.Domain.Entities.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RosaryForToday.Domain.Entities.RosaryType", "RosaryType")
                        .WithMany("RosaryDaySchedules")
                        .HasForeignKey("RosaryTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("RosaryType");
                });

            modelBuilder.Entity("RosaryForToday.Domain.Entities.RosaryReflection", b =>
                {
                    b.HasOne("RosaryForToday.Domain.Entities.Language", "Language")
                        .WithMany("RosaryReflections")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RosaryForToday.Domain.Entities.RosaryType", "RosaryType")
                        .WithMany("RosaryReflections")
                        .HasForeignKey("RosaryTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("RosaryType");
                });

            modelBuilder.Entity("RosaryForToday.Domain.Entities.RosaryType", b =>
                {
                    b.HasOne("RosaryForToday.Domain.Entities.Language", "Language")
                        .WithMany("RosaryTypes")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Language");
                });

            modelBuilder.Entity("RosaryForToday.Domain.Entities.Language", b =>
                {
                    b.Navigation("RosaryReflections");

                    b.Navigation("RosaryTypes");
                });

            modelBuilder.Entity("RosaryForToday.Domain.Entities.RosaryType", b =>
                {
                    b.Navigation("RosaryDaySchedules");

                    b.Navigation("RosaryReflections");
                });
#pragma warning restore 612, 618
        }
    }
}
